services:
    app.planet.earth_government:
        class: AppBundle\Planet\PlanetGovernment
        factory: ["AppBundle\\Factory\\PlanetGovernmentFactory", "createPlanetGovernment"]
        arguments:
            - "Earth"
    app.planet.mars_government:
        class: AppBundle\Planet\PlanetGovernment
        factory: ["AppBundle\\Factory\\PlanetGovernmentFactory", "createPlanetGovernment"]
        arguments:
            - "Mars"
    app.planet.uranus_government:
        class: AppBundle\Planet\PlanetGovernment
        factory: ["AppBundle\\Factory\\PlanetGovernmentFactory", "createPlanetGovernment"]
        arguments:
            - "Uranus"