parameters:
#    parameter_name: value

services:
    app.security.guard:
        class: AppBundle\Security\FormLoginGuard
        arguments:
            - "@security.password_encoder"
            - "@logger"
